# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'


def common
  pod 'ReactorKit'
  pod 'RxSwift'
  pod 'RxSwiftExt'
  pod 'RxCocoa'
  pod 'RxKeyboard'
  pod 'RxGesture'
  pod 'RxRelay'
  pod 'RxDataSources'
  pod 'RxViewController'
  pod 'SwiftyUserDefaults'
  pod 'SwiftyBeaver'
  pod 'SwiftLint'
  pod 'Then'
  pod 'SwiftyJSON'
  pod 'FirebaseCrashlytics'
  pod 'Reusable'
end

def ui
  pod 'SnapKit'
  pod 'Kingfisher'
  pod 'BonMot'
  pod 'lottie-ios'
  #pod 'Charts'
  pod 'PanModal'
  pod 'NVActivityIndicatorView'
end

def networking
  pod 'Moya/RxSwift'
end

target 'DataCubeDemo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  common
  ui
  networking

  # Pods for DataCubeDemo

  target 'DataCubeDemoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'DataCubeDemoUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
